// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.domain.repository.StopShadowSessionRequestDomainRepository;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.StartShadowSessionRequest;
import com.probestack.forgestudio.design.model.StopShadowSessionRequest;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class ShadowsServiceTest {

    private final StopShadowSessionRequestDomainRepository repository = mock(StopShadowSessionRequestDomainRepository.class);
    private final ShadowsService service = new ShadowsService(repository, mock(BusinessOperationLogger.class));

    private static StopShadowSessionRequest entity() {
        StopShadowSessionRequest entity = new StopShadowSessionRequest();
        return entity;
    }

    @Test
    void getShadowReport_returnsTheEntityWhenItExists() {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.of(entity()));
        var response = service.getShadowReport(UUID.fromString("00000000-0000-0000-0000-000000000001"), true, "id-1");
        assertTrue(response.getStatusCode().is2xxSuccessful());
        assertNotNull(response.getBody());
    }

    @Test
    void getShadowReport_failsWhenTheEntityDoesNotExist() {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.empty());
        assertThrows(RuntimeException.class, () -> service.getShadowReport(UUID.fromString("00000000-0000-0000-0000-000000000001"), true, "id-1"));
    }

    @Test
    void getShadowStatus_returnsTheEntityWhenItExists() {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.of(entity()));
        var response = service.getShadowStatus(UUID.fromString("00000000-0000-0000-0000-000000000001"));
        assertTrue(response.getStatusCode().is2xxSuccessful());
        assertNotNull(response.getBody());
    }

    @Test
    void getShadowStatus_failsWhenTheEntityDoesNotExist() {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.empty());
        assertThrows(RuntimeException.class, () -> service.getShadowStatus(UUID.fromString("00000000-0000-0000-0000-000000000001")));
    }

    @Test
    void startShadowSession_isNotImplementedUntilBusinessLogicExists() {
        assertThrows(RuntimeException.class, () -> service.startShadowSession(new StartShadowSessionRequest()));
    }

    @Test
    void stopShadowSession_isNotImplementedUntilBusinessLogicExists() {
        assertThrows(RuntimeException.class, () -> service.stopShadowSession(UUID.fromString("00000000-0000-0000-0000-000000000001"), entity()));
    }

}
