// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.api;

import com.probestack.forgestudio.design.advice.GlobalExceptionHandler;
import com.probestack.forgestudio.design.config.validation.ValidationProperties;
import com.probestack.forgestudio.design.domain.repository.StopShadowSessionRequestDomainRepository;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.StopShadowSessionRequest;
import com.probestack.forgestudio.design.service.ShadowsService;
import com.probestack.forgestudio.design.validation.GeneratedRequestValidator;
import jakarta.validation.Validation;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

class ShadowsApiControllerIntegrationTest {

    private final StopShadowSessionRequestDomainRepository repository = mock(StopShadowSessionRequestDomainRepository.class);
    private MockMvc mockMvc;

    private static StopShadowSessionRequest entity() {
        StopShadowSessionRequest entity = new StopShadowSessionRequest();
        return entity;
    }

    @BeforeEach
    void setUp() {
        ShadowsService service = new ShadowsService(repository, mock(BusinessOperationLogger.class));
        ValidationProperties properties = new ValidationProperties();
        properties.setEnabled(true);
        GeneratedRequestValidator validator = new GeneratedRequestValidator(properties,
                Validation.buildDefaultValidatorFactory().getValidator());
        ShadowsApiController controller = new ShadowsApiController(service, validator);
        mockMvc = MockMvcBuilders.standaloneSetup(controller)
                .setControllerAdvice(new GlobalExceptionHandler())
                .addPlaceholderValue("openapi.shadowMirror.base-path", "/v1")
                .build();
    }

    @Test
    void startShadowSession_isNotImplementedUntilBusinessLogicExists() throws Exception {
        mockMvc.perform(request(HttpMethod.POST, "/v1/shadows")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"serviceName\":\"payment-processor\",\"environment\":\"PRODUCTION\",\"shadowVersion\":\"v2.5.0\",\"baselineVersion\":\"v2.4.1\",\"mirrorPercent\":10,\"durationMinutes\":30,\"samplePaths\":[\"/api/v1/charge\",\"/api/v1/refund\"],\"excludePaths\":[\"/api/v1/admin/*\",\"/actuator/*\"],\"compareMode\":\"JSON_DEEP_EQUAL\",\"redactPii\":true}"))
                .andExpect(status().isNotImplemented());
    }

    @Test
    void getShadowStatus_returnsTheEntity() throws Exception {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.of(entity()));
        mockMvc.perform(request(HttpMethod.GET, "/v1/shadows/{shadowId}", "00000000-0000-0000-0000-000000000001"))
                .andExpect(status().is2xxSuccessful());
    }

    @Test
    void getShadowStatus_isNotFoundWhenTheEntityDoesNotExist() throws Exception {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.empty());
        mockMvc.perform(request(HttpMethod.GET, "/v1/shadows/{shadowId}", "00000000-0000-0000-0000-000000000001"))
                .andExpect(status().isNotFound());
    }

    @Test
    void getShadowReport_returnsTheEntity() throws Exception {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.of(entity()));
        mockMvc.perform(request(HttpMethod.GET, "/v1/shadows/{shadowId}/report", "00000000-0000-0000-0000-000000000001"))
                .andExpect(status().is2xxSuccessful());
    }

    @Test
    void getShadowReport_isNotFoundWhenTheEntityDoesNotExist() throws Exception {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.empty());
        mockMvc.perform(request(HttpMethod.GET, "/v1/shadows/{shadowId}/report", "00000000-0000-0000-0000-000000000001"))
                .andExpect(status().isNotFound());
    }

    @Test
    void stopShadowSession_isNotImplementedUntilBusinessLogicExists() throws Exception {
        mockMvc.perform(request(HttpMethod.POST, "/v1/shadows/{shadowId}/stop", "00000000-0000-0000-0000-000000000001")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"reason\":\"Sufficient samples collected; ready to review report.\",\"generateReport\":true}"))
                .andExpect(status().isNotImplemented());
    }

}
