// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.persistence.mongodb.adapter;

import com.probestack.forgestudio.design.model.StopShadowSessionRequest;
import com.probestack.forgestudio.design.persistence.mongodb.document.StopShadowSessionRequestDocument;
import com.probestack.forgestudio.design.persistence.mongodb.repository.StopShadowSessionRequestMongoRepository;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.ArgumentMatchers;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class StopShadowSessionRequestMongoPersistenceAdapterTest {

    private final StopShadowSessionRequestMongoRepository repository = mock(StopShadowSessionRequestMongoRepository.class);
    private final StopShadowSessionRequestMongoPersistenceAdapter adapter = new StopShadowSessionRequestMongoPersistenceAdapter(repository);

    private static StopShadowSessionRequest domain() {
        StopShadowSessionRequest domain = new StopShadowSessionRequest();
        return domain;
    }

    private static StopShadowSessionRequestDocument stored() {
        StopShadowSessionRequestDocument stored = new StopShadowSessionRequestDocument();
        return stored;
    }

    @Test
    void save_mapsToThePersistenceModelAndBack() {
        when(repository.save(ArgumentMatchers.any(StopShadowSessionRequestDocument.class))).thenAnswer(invocation -> invocation.getArgument(0));
        StopShadowSessionRequest saved = adapter.save(domain());
        ArgumentCaptor<StopShadowSessionRequestDocument> captor = ArgumentCaptor.forClass(StopShadowSessionRequestDocument.class);
        verify(repository).save(captor.capture());
        assertNotNull(saved);
    }

    @Test
    void findById_mapsAStoredEntityToTheDomainModel() {
        when(repository.findById("id-1")).thenReturn(Optional.of(stored()));
        Optional<StopShadowSessionRequest> found = adapter.findById("id-1");
        assertTrue(found.isPresent());
    }

    @Test
    void findById_isEmptyWhenNothingIsStored() {
        when(repository.findById("id-1")).thenReturn(Optional.empty());
        assertTrue(adapter.findById("id-1").isEmpty());
    }

    @Test
    void findAll_mapsEveryStoredEntity() {
        when(repository.findAll()).thenReturn(List.of(stored()));
        List<StopShadowSessionRequest> all = adapter.findAll();
        assertEquals(1, all.size());
    }

    @Test
    void existsById_delegatesToTheRepository() {
        when(repository.existsById("id-1")).thenReturn(true);
        assertTrue(adapter.existsById("id-1"));
    }

    @Test
    void deleteById_delegatesToTheRepository() {
        adapter.deleteById("id-1");
        verify(repository).deleteById("id-1");
    }

    @Test
    void count_delegatesToTheRepository() {
        when(repository.count()).thenReturn(3L);
        assertEquals(3L, adapter.count());
    }

}
